### ISSUE TITLE
make build fails with target build-html

### ISSUE THREAD

**Issue by happybeing** [untitaker/taskrs#21]
`make build` fails on target build-html

This looks like it might be due to it expecting site/.htaccess to exist?

Workaround:

```
make build-js build-css
cp site/index.html build
```

**Comment by untitaker** [comment]
`.htaccess` does exist in the repo.

**Comment by untitaker** [comment]
I can't really reproduce the errors you're getting. But I've pushed an update to the Makefile in case the execution order is different in your case.

Does the `build` directory exist?

**Comment by happybeing** [comment]
build didn't exist before I did "make build-css"

You're right, .htaccess is there. Ashamed to admit I forgot to "ls -a" :blush:

**Comment by untitaker** [comment]
Ok cool. I think the Makefile is fixed and will now create the directory properly.

**Comment by happybeing** [comment]
Hmm... I may be your worst nightmare. To test your fix I did...

```
git clone blah
cd 
make
make install # as I wasn't sure if it did everything
make build
```

This failed:

```
make build
mkdir -p build/js
webpack js/app.js build/js/all.js
Hash: da34f2295eba8a79b05e
Version: webpack 1.13.2
Time: 2322ms
 Asset     Size  Chunks             Chunk Names
all.js  2.13 MB       0  [emitted]  main
   [0] ./js/app.js 36.8 kB {0} [built]
   [1] ./lib/remotestorage.amd.js 347 kB {0} [built]
   [6] ./js/model.js 8.05 kB {0} [built]
   [7] ./js/utils.js 2.12 kB {0} [built]
    + 283 hidden modules
mkdir -p build/css build/fonts
cp -R bower_components/bootstrap/dist/fonts/* build/fonts/
lessc css/app.less | grep -v removethisline > build/css/all.css
mkdir build
mkdir: cannot create directory ‘build’: File exists
Makefile:23: recipe for target 'build-html' failed
```

**Comment by untitaker** [comment]
It appears that `build` is a file, please remove it and try again.

**Comment by happybeing** [comment]
I cloned and typed

```
make
```

There's no file or directory called 'build' after this. So then...

```
make build
```

This gives the error:

```
mkdir -p build/js
webpack js/app.js build/js/all.js
Hash: da34f2295eba8a79b05e
Version: webpack 1.13.2
Time: 2348ms
 Asset     Size  Chunks             Chunk Names
all.js  2.13 MB       0  [emitted]  main
   [0] ./js/app.js 36.8 kB {0} [built]
   [1] ./lib/remotestorage.amd.js 347 kB {0} [built]
   [6] ./js/model.js 8.05 kB {0} [built]
   [7] ./js/utils.js 2.12 kB {0} [built]
    + 283 hidden modules
mkdir -p build/css build/fonts
cp -R bower_components/bootstrap/dist/fonts/* build/fonts/
lessc css/app.less | grep -v removethisline > build/css/all.css
mkdir build
mkdir: cannot create directory ‘build’: File exists
```

build now exists but is a _directory_ containing sub-directories: css fonts js

**Comment by untitaker** [comment]
NOW it should work

**Comment by happybeing** [comment]
I reckon one more go might do it :wink: here's what I get now (and site looks fine, contains .htaccess and index.html as expected):

```
mkdir -p build/css build/fonts
cp -R bower_components/bootstrap/dist/fonts/* build/fonts/
lessc css/app.less | grep -v removethisline > build/css/all.css
mkdir -p build
cp -R site/{*,.htaccess} build/
cp: cannot stat ‘site/{*,.htaccess}’: No such file or directory
Makefile:25: recipe for target 'build-html' failed
make: *** [build-html] Error 1
```

BTW If I type `cp -R site/{*,.htaccess} build/` manually it works.

EDIT: After doing the above manually I have a working taskrs tho, so I'm running... thanks for your help :smile:

**Comment by untitaker** [comment]
Eh, which operating system are you running on? What does `make --version` print?

**Comment by happybeing** [comment]
Debian (LMDE Jesse I think).

make --version gives

```
GNU Make 4.0
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I have taskrs working now. There seems to be a glitch when making a task - a new task doesn't show until I toggle "show comleted tasks" on and off. (I was just typing a task name and hitting return).

**Comment by untitaker** [comment]
Yeah about that... This was my first mayor app in JavaScript. I currently don't use it and it probably needs a rewrite before I'll ever do.

On 1 September 2016 00:06:13 CEST, theWebalyst notifications@github.com wrote:

> Debian (LMDE Jesse I think).
> 
> make --version gives
> 
> ```
> GNU Make 4.0
> Built for x86_64-pc-linux-gnu
> Copyright (C) 1988-2013 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later
> <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> ```
> 
> I have taskrs working now. There seems to be a glitch when making a
> task - a new task doesn't show until I toggle "show comleted tasks" on
> and off. (I was just typing a task name and hitting return).
> 
> ## 
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/untitaker/taskrs/issues/21#issuecomment-243917473

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by happybeing** [comment]
No problem, thanks for your help. Should make a nice demo with SAFE Network.
